### ISSUE TITLE
`Go` port

### ISSUE THREAD

**Issue by bartekpacia** [AIS-Bonn/attitude_estimator#4]
Hi!

First of all, thank you for this awesome library. It greatly helped [us](https://github.com/knei-knurow) in [lidar-2d-to-3d project](https://github.com/knei-knurow/lidar-2d-to-3d). 

We were mainly using [the Go language](https://go.dev) for and we didn't find any versions of your library in Go, so [we created one](https://github.com/knei-knurow/attestimator) (We also considered other options like using [cgo](https://pkg.go.dev/cmd/cgo) or [SWIG](http://www.swig.org/Doc3.0/Go.html), but in the end we decided that rewriting the library would be the best option). We think linking to it somewhere (in README?) might be useful for other people in our situation, so they won't have to rewrite the library like we had to. [Here's the repo](https://github.com/knei-knurow/attestimator).

Again, thanks a lot for you great piece of software!

**Comment by pallgeuer** [comment]
I have added a note to the General Overview of the library.
